### ISSUE TITLE
Quran Zip file

### ISSUE THREAD

**Issue by Nourtirga** [3llomi/AyatuRabbi_Quran#2]
Can you provide us with the zip file stored in your Firebase account, Without it the app doesn't work!

**Comment by 3llomi** [comment]
Sure, it's publicly available 

data_320.zip:
https://firebasestorage.googleapis.com/v0/b/ayaturabbi-c9cd5.appspot.com/o/quran_files%2Fdata_320.zip?alt=media&token=74254622-6615-4bbb-9326-1b57322406cb

data_480.zip:
https://firebasestorage.googleapis.com/v0/b/ayaturabbi-c9cd5.appspot.com/o/quran_files%2Fdata_480.zip?alt=media&token=e4aece67-8461-42d1-88d0-ed9fb2cfc109

data_800.zip:
https://firebasestorage.googleapis.com/v0/b/ayaturabbi-c9cd5.appspot.com/o/quran_files%2Fdata_800.zip?alt=media&token=49f872f6-28e3-4bfb-aa82-207947a7fdf3

data_1024.zip:
https://firebasestorage.googleapis.com/v0/b/ayaturabbi-c9cd5.appspot.com/o/quran_files%2Fdata_1024.zip?alt=media&token=2f74f9f3-44c0-4e9a-b6d4-6ddfb808e00a

data_1260.zip:
https://firebasestorage.googleapis.com/v0/b/ayaturabbi-c9cd5.appspot.com/o/quran_files%2Fdata_1260.zip?alt=media&token=bfcfefc1-02c7-495e-9429-4bdbe561d3b2
